import { OpenRouterCompletionMeta, OpenRouterUsage } from '../../OpenRouterClient';

export type RPGLiteModelPurpose = 'creator' | 'prose' | 'editor' | 'rater';

export type RPGLiteMessageRole = 'user' | 'assistant';

export interface RPGLiteMessageGenerationMeta {
  purpose: RPGLiteModelPurpose;
  model: string;
  promptChars: number;
  completionChars: number;
  durationMs: number;
  usage?: OpenRouterUsage;
  totalCostUsd?: number;
}

export interface RPGLiteMessageVersion {
  content: string;
  createdAt: number;
  generation?: RPGLiteMessageGenerationMeta;
}

/**
 * Present on an opening message that was generated with "Shake things up":
 * the brainstormed divergent opening directions and which one was randomly chosen.
 */
export interface RPGLiteOpeningShake {
  directions: string[];
  chosenIndex: number;
}

export interface RPGLiteChatMessage {
  id: string;
  role: RPGLiteMessageRole;
  content: string;
  createdAt: number;
  editedAt?: number;
  generation?: RPGLiteMessageGenerationMeta;
  // Support for multiple versions (e.g., from retry)
  versions?: RPGLiteMessageVersion[];
  activeVersionIndex?: number;
  /** Base64 data URLs of images generated by the model (e.g. "data:image/png;base64,..."). */
  images?: string[];
  /** Present on the opening message when "Shake things up" produced a random opening direction. */
  openingShake?: RPGLiteOpeningShake;
}

export interface RPGLiteSession {
  id: string;
  title: string;
  createdAt: number;
  updatedAt: number;

  systemPrompt: string;
  prefixContext: string;

  narratorPurpose: RPGLiteModelPurpose;
  maxContextMessages: number;
  temperature?: number;  // Optional temperature override for this session (0-2)

  /** Maximum number of retries allowed. null = unlimited. Defaults to 10 when undefined. */
  retryLimit?: number | null;
  /** How many retries have been used in this session. */
  retriesUsed?: number;

  /** When true, opening generation is "shaken up" with a random divergent direction. Per-session. */
  shakeOpenings?: boolean;

  conversation: RPGLiteChatMessage[];
  clipboard?: string;
}

export interface RPGLiteStartPreset {
  id: string;
  name: string;
  createdAt: number;
  updatedAt: number;

  title: string;
  systemPrompt: string;
  prefixContext: string;
  narratorPurpose?: RPGLiteModelPurpose; // Optional: undefined means use default
  maxContextMessages: number;
  /** When true, sessions started from this template shake up the opening by default. */
  shakeOpenings?: boolean;
}

export interface RPGLiteActionButton {
  id: string;
  label: string;
  text: string;
  order: number;
  createdAt: number;
  updatedAt: number;
}

export function mapCompletionMetaToGenerationMeta(
  purpose: RPGLiteModelPurpose,
  meta: OpenRouterCompletionMeta
): RPGLiteMessageGenerationMeta {
  return {
    purpose,
    model: meta.model,
    promptChars: meta.promptChars,
    completionChars: meta.completionChars,
    durationMs: meta.durationMs,
    ...(meta.usage ? { usage: meta.usage } : {}),
    ...(typeof meta.totalCostUsd === 'number' ? { totalCostUsd: meta.totalCostUsd } : {})
  };
}


