import { OpenRouterCompletionMeta, OpenRouterUsage } from '../../OpenRouterClient';

export type RPGLiteModelPurpose = 'creator' | 'prose' | 'editor' | 'rater';

export type RPGLiteMessageRole = 'user' | 'assistant';

/**
 * How periodical "story so far" summaries are produced.
 * - 'off':  no summaries; context uses the last-N recency window (maxContextMessages).
 * - 'lean': rolling — each checkpoint folds the previous summary with only the new
 *            interval's messages. Cheap and low-context-friendly, but summary errors
 *            compound because earlier raw messages are never re-read.
 * - 'full': accurate — each checkpoint re-summarizes ALL messages up to the boundary
 *            from scratch. No drift, but cost grows with story length and it needs a
 *            model that can hold the whole covered prefix in one call.
 */
export type RPGLiteSummaryMode = 'off' | 'lean' | 'full';

export interface RPGLiteMessageGenerationMeta {
  purpose: RPGLiteModelPurpose;
  model: string;
  promptChars: number;
  completionChars: number;
  durationMs: number;
  usage?: OpenRouterUsage;
  totalCostUsd?: number;
}

export interface RPGLiteMessageVersion {
  content: string;
  createdAt: number;
  generation?: RPGLiteMessageGenerationMeta;
}

/**
 * Present on an opening message that was generated with "Shake things up":
 * the brainstormed divergent opening directions and which one was randomly chosen.
 */
export interface RPGLiteOpeningShake {
  directions: string[];
  chosenIndex: number;
}

export interface RPGLiteChatMessage {
  id: string;
  role: RPGLiteMessageRole;
  content: string;
  createdAt: number;
  editedAt?: number;
  generation?: RPGLiteMessageGenerationMeta;
  // Support for multiple versions (e.g., from retry)
  versions?: RPGLiteMessageVersion[];
  activeVersionIndex?: number;
  /** Base64 data URLs of images generated by the model (e.g. "data:image/png;base64,..."). */
  images?: string[];
  /** Present on the opening message when "Shake things up" produced a random opening direction. */
  openingShake?: RPGLiteOpeningShake;
}

/**
 * A cumulative "story so far" summary anchored to a conversation prefix length.
 * A milestone reflects conversation[0 .. coveredCount-1]. Anchoring by a prefix
 * COUNT (not a message id) makes retry-safety trivial: any milestone whose
 * coveredCount exceeds the point of a history mutation is simply dropped.
 */
export interface RPGLiteMilestone {
  id: string;
  /** Number of conversation messages this summary covers (summarizes conversation[0 .. coveredCount-1]). */
  coveredCount: number;
  /** The cumulative "story so far" summary text. */
  summary: string;
  createdAt: number;
  generation?: RPGLiteMessageGenerationMeta;
}

export interface RPGLiteSession {
  id: string;
  title: string;
  createdAt: number;
  updatedAt: number;

  systemPrompt: string;
  prefixContext: string;

  /**
   * Deterministic seed for {{selectonefrom …}} dice-roll placeholders in the system
   * prompt / prefix context. A fixed seed keeps every roll stable across turns so the
   * chosen scenario stays coherent while playing; a new seed is minted whenever the
   * opening message is (re)generated, so retrying the first prompt reshuffles the picks.
   */
  selectionSeed: number;

  narratorPurpose: RPGLiteModelPurpose;
  maxContextMessages: number;
  temperature?: number;  // Optional temperature override for this session (0-2)

  /** Maximum number of retries allowed. null = unlimited. Defaults to unlimited when undefined. */
  retryLimit?: number | null;
  /** How many retries have been used in this session. */
  retriesUsed?: number;

  /** When true, opening generation is "shaken up" with a random divergent direction. Per-session. */
  shakeOpenings?: boolean;

  /** Periodical "story so far" summary mode. Defaults to 'off' when undefined. */
  summaryMode?: RPGLiteSummaryMode;
  /** How many new messages must accumulate past the last milestone before a new one is generated. Defaults to 50 when undefined. */
  summaryInterval?: number;
  /** Cumulative "story so far" summaries, each anchored to a conversation prefix length. */
  milestones?: RPGLiteMilestone[];

  conversation: RPGLiteChatMessage[];
  clipboard?: string;
}

export interface RPGLiteStartPreset {
  id: string;
  name: string;
  createdAt: number;
  updatedAt: number;

  title: string;
  systemPrompt: string;
  prefixContext: string;
  narratorPurpose?: RPGLiteModelPurpose; // Optional: undefined means use default
  maxContextMessages: number;
  /** When true, sessions started from this template shake up the opening by default. */
  shakeOpenings?: boolean;
  /** Default summary mode for sessions started from this template. */
  summaryMode?: RPGLiteSummaryMode;
  /** Default milestone interval (messages) for sessions started from this template. */
  summaryInterval?: number;
}

export interface RPGLiteActionButton {
  id: string;
  label: string;
  text: string;
  order: number;
  createdAt: number;
  updatedAt: number;
}

export function mapCompletionMetaToGenerationMeta(
  purpose: RPGLiteModelPurpose,
  meta: OpenRouterCompletionMeta
): RPGLiteMessageGenerationMeta {
  return {
    purpose,
    model: meta.model,
    promptChars: meta.promptChars,
    completionChars: meta.completionChars,
    durationMs: meta.durationMs,
    ...(meta.usage ? { usage: meta.usage } : {}),
    ...(typeof meta.totalCostUsd === 'number' ? { totalCostUsd: meta.totalCostUsd } : {})
  };
}


