import JSZip from 'jszip';

export class HelloWorldEpubGenerator {
    private zip: JSZip;
    private uuid: string;
    private title: string;
    private author: string;
    private timestamp: string;

    constructor() {
        this.zip = new JSZip();
        this.uuid = this.generateUUID();
        this.title = 'Hello World';
        this.author = 'Expert System';
        this.timestamp = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
    }

    private generateUUID(): string {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
            const r = Math.random() * 16 | 0;
            const v = c === 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
    }

    private escapeXml(text: string): string {
        return text
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    }

    private createMimetype(): string {
        return 'application/epub+zip';
    }

    private createContainer(): string {
        return `<?xml version="1.0" encoding="UTF-8"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
    <rootfiles>
        <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
    </rootfiles>
</container>`;
    }

    private createContent(): string {
        return `<?xml version="1.0" encoding="UTF-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="BookId">
    <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
        <dc:identifier id="BookId">${this.escapeXml(this.uuid)}</dc:identifier>
        <dc:title>${this.escapeXml(this.title)}</dc:title>
        <dc:creator>${this.escapeXml(this.author)}</dc:creator>
        <dc:language>en</dc:language>
        <dc:date>${this.timestamp}</dc:date>
        <meta property="dcterms:modified">${this.timestamp}</meta>
    </metadata>
    <manifest>
        <item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/>
        <item id="chapter1" href="chapter1.xhtml" media-type="application/xhtml+xml"/>
        <item id="stylesheet" href="styles.css" media-type="text/css"/>
    </manifest>
    <spine>
        <itemref idref="chapter1"/>
    </spine>
</package>`;
    }

    private createNavigation(): string {
        return `<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops">
<head>
    <title>Navigation</title>
    <link rel="stylesheet" href="styles.css"/>
</head>
<body>
    <nav epub:type="toc">
        <h1>Table of Contents</h1>
        <ol>
            <li><a href="chapter1.xhtml">Hello World</a></li>
        </ol>
    </nav>
</body>
</html>`;
    }

    private createChapter(): string {
        return `<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Hello World</title>
    <link rel="stylesheet" href="styles.css"/>
</head>
<body>
    <h1>Hello World</h1>
    <p>This is a minimal EPUB generated by the Expert System.</p>
    <p>It contains just one chapter with this simple "Hello World" message.</p>
    <p>The EPUB was created using a completely new generator based on working examples from the web.</p>
    <p>Generated on: ${this.timestamp}</p>
</body>
</html>`;
    }

    private createStyles(): string {
        return `body {
    font-family: Georgia, serif;
    line-height: 1.6;
    margin: 2em;
    max-width: 600px;
}

h1 {
    color: #333;
    border-bottom: 2px solid #333;
    padding-bottom: 0.5em;
}

p {
    margin: 1em 0;
    text-align: justify;
}`;
    }

    public async generate(): Promise<Blob> {
        // Add mimetype (uncompressed, first file)
        this.zip.file('mimetype', this.createMimetype(), { compression: 'STORE' });
        
        // Add META-INF
        this.zip.file('META-INF/container.xml', this.createContainer());
        
        // Add OEBPS content
        this.zip.file('OEBPS/content.opf', this.createContent());
        this.zip.file('OEBPS/nav.xhtml', this.createNavigation());
        this.zip.file('OEBPS/chapter1.xhtml', this.createChapter());
        this.zip.file('OEBPS/styles.css', this.createStyles());

        // Generate the EPUB
        const content = await this.zip.generateAsync({
            type: 'blob',
            mimeType: 'application/epub+zip',
            compressionOptions: {
                level: 9
            }
        });

        return content;
    }

    public setTitle(title: string): void {
        this.title = title;
    }

    public setAuthor(author: string): void {
        this.author = author;
    }
} 